# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-16 20:38
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEvents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=127)),
                ('summary', models.CharField(max_length=511, null=True)),
                ('description', models.TextField(null=True)),
                ('event_created_at', models.DateTimeField(null=True)),
                ('event_updated_at', models.DateTimeField(null=True)),
                ('event_start_at', models.DateTimeField(null=True)),
                ('event_end_at', models.DateTimeField(null=True)),
                ('event_link', models.CharField(max_length=511, null=True)),
                ('organizer_name', models.CharField(max_length=127, null=True)),
                ('organizer_email', models.CharField(max_length=511, null=True)),
                ('creator_name', models.CharField(max_length=127, null=True)),
                ('creator_email', models.CharField(max_length=511, null=True)),
                ('attendees', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('location', models.CharField(max_length=511, null=True)),
                ('other_details', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
